SET TRANSACTION;

/*
teste
*/

CREATE TABLE OutraInformacao (
OutraInformacaoID INT generated by default as identity,
EmpresaID integer not null,
Periodo date not null,
TipoDocumento smallint not null,
Descricao varchar(100) COLLATE WIN_PTBR,
Informacoes BLOB sub_type 0,
CONSTRAINT PK_OutraInformacao PRIMARY KEY (OutraInformacaoID)
);

/*
teste2
*/

COMMIT;

SET TRANSACTION;

SET TERM # ;

EXECUTE BLOCK AS
    DECLARE Emp INT;
    DECLARE Per Date;
    DECLARE Info blob sub_type 0;
BEGIN

    FOR SELECT EmpresaID, Periodo, Informacoes
        FROM Fechamento
		WHERE Informacoes IS NOT NULL		
    INTO :EMP, :Per, :Info DO
    BEGIN
        INSERT INTO OutraInformacao (EmpresaID, Periodo, TipoDocumento, Descricao, Informacoes) 
        VALUES (:Emp, :Per, 10, 'Nota Explicativa', :Info);

    END
END#
SET TERM ; #

ALTER TABLE Fechamento DROP Informacoes;

CREATE TABLE OutraInformacaoConta (OutraInformacaoContaID INT generated by default as identity,
OutraInformacaoID integer NOT NULL,
EmpresaID integer NOT NULL,
Periodo date not null,
PlanoEmpresaId smallint NOT NULL, 
Referencia varchar(12) COLLATE WIN_PTBR,
DlpaDmpl booleano,
Dre booleano,
BalancoPatrimonial booleano,
CONSTRAINT PK_ContaOutInf PRIMARY KEY (OutraInformacaoContaID),
CONSTRAINT FK_ContaOutInf_PlanoEmpresas FOREIGN KEY (EmpresaID, PlanoEmpresaId) REFERENCES PlanoEmpresas (EmpresaID, PlanoEmpresaID) ON UPDATE CASCADE, 
CONSTRAINT FK_ContaOutInf_OutraInformacao FOREIGN KEY (OutraInformacaoID) REFERENCES OutraInformacao(OutraInformacaoID) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE ENQUADRAMENTOS ADD S1020 TIMESTAMP;
      
UPDATE Controle SET Versao = '22.9.9.8';

COMMIT;